In [1]:
import numpy as np

In [10]:
alpha = np.array([1., 2., 3.,4.,5.,])
print(alpha.shape)
print(alpha.dtype)

bravo = np.array([1, 2, 3, 4, 5, 6, 7], np.int64)
print(bravo.shape)
print(bravo.dtype)

(5,)
float64
(7,)
int64


In [13]:
charlie = np.array(['1', 2, '3'])
print(charlie.dtype)

<U1


In [17]:
xray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(xray)
xray.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [21]:
cold = np.array([[1],[2],[3]])
print(cold)

print(cold.shape) # describes dimensions of array

[[1]
 [2]
 [3]]
(3, 1)


In [22]:
X = np.array([[3,5],[5,7]])
Y = np.array([[7,5],[5,3]])
print(X+Y)

[[10 10]
 [10 10]]


In [23]:
X + 4

array([[ 7,  9],
       [ 9, 11]])

In [25]:
X2 = np.array([[1,2],[3,4]])
# X2 - [4,5]
# X2 - [[4], [5]]
X2 - (4,5)
# print(X2 - (4, 5))
print(X2)

[[1 2]
 [3 4]]
